#!/bin/sh

if [ ! -e $HOME/.bin ] ; then
    mkdir $HOME/.bin
fi
wget https://github.com/direnv/direnv/releases/download/v2.17.0/direnv.linux-amd64
chmod 755 direnv.linux-amd64
mv direnv.linux-amd64 $HOME/.bin/direnv

echo 'eval "$(direnv hook zsh)"' >> $HOME/dotfiles/files/zsh.d/inits/99_local.zsh

