#!/bin/sh

WORKDIR=/tmp/tmpworkdir
if [ ! -e $WORKDIR ] ; then
    mkdir $WORKDIR
fi
cd $WORKDIR

wget https://releases.hashicorp.com/terraform/0.11.7/terraform_0.11.7_linux_amd64.zip
unzip terraform_0.11.7_linux_amd64.zip
if [ ! -e $HOME/.bin ] ; then
    mkdir $HOME/.bin
fi
mv terraform $HOME/.bin
rm -rf $WORKDIR