#!/bin/sh

WORKDIR=/tmp/tmpworkdir
if [ ! -e $WORKDIR ] ; then
    mkdir $WORKDIR
fi
cd $WORKDIR

wget https://releases.hashicorp.com/packer/1.2.5/packer_1.2.5_linux_amd64.zip
unzip packer_1.2.5_linux_amd64.zip
if [ ! -e $HOME/.bin ] ; then
    mkdir $HOME/.bin
fi
mv packer $HOME/.bin
rm -rf $WORKDIR
