export LANG="ja_JP.UTF-8"
export LC_ALL=ja_JP.UTF-8

export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"
export DefaultIMModule=fcitx

fcitx-autostart
xrdb -load ~/.Xresources

firefox &
urxvt &

fvwm
