(setq kill-whole-line t)
(setq scroll-conservatively 1)
(setq-default tab-width 4)
(setq-default indent-tabs-mode nil)
(delete-selection-mode t)

(global-auto-revert-mode t)
(put 'upcase-region 'disabled nil)
(put 'downcase-region 'disabled nil)

(bind-key* "C-x ," 'expand-abbrev)
(bind-key* "C-x ." 'dabbrev-expand)
(bind-key* "C-x t" 'query-replace)
(bind-key* "C-x i a" 'all-indent)
(bind-key* "C-x i r" 'indent-region)
(bind-key* "C-x i a" 'back-to-indentation)
(bind-key* "C-x M-)" 'kmacro-save)
(bind-key* "M-n" 'scroll-up-one-line)
(bind-key* "M-p" 'scroll-down-one-line)
(bind-key* "M-(" 'insert-parentheses)
(bind-key* "M-[" 'insert-brackets)
(bind-key* "M-{" 'insert-braces)
(bind-key* "M-'" 'insert-single-quotes)
(bind-key* "M-\"" 'insert-double-quotes)
(bind-key* "M-<" 'insert-angle-brackets)
