(use-package web-mode
  :mode (("\\.ctp\\'"   . web-mode)
         ("\\.html?\\'" . web-mode)
         ("\\.tt\\'" . web-mode))
  :config
  (setq web-mode-markup-indent-offset 2)
  (setq web-mode-css-indent-offset 2)
  (setq web-mode-script-offset 2)
  (setq web-mode-code-indent-offset 2)
  (setq web-mode-block-indent 2)
  (setq web-mode-template-toolkit-offset 0)
  (setq web-mode-enable-auto-closing t)
  (progn
    (setq web-mode-comment-face ((t (:foreground "#D9333F"))))
    (setq web-mode-css-at-rule-face ((t (:foreground "#FF7F00"))))
    (setq web-mode-css-pseudo-class-face ((t (:foreground "#FF7F00"))))
    (setq web-mode-css-rule-face ((t (:foreground "#A0D8EF"))))
    (setq web-mode-doctype-face ((t (:foreground "#82AE46"))))
    (setq web-mode-html-attr-name-face ((t (:foreground "#C97586"))))
    (setq web-mode-html-attr-value-face ((t (:foreground "#82AE46"))))
    (setq web-mode-html-tag-face ((t (:foreground "#E6B422" :weight bold))))
    (setq web-mode-server-comment-face ((t (:foreground "#D9333F"))))))
